### ISSUE TITLE
Regen Problem

### ISSUE THREAD

**Issue by charliebrown777** [Satellile/yara#3] opened 2024-02-19 19:20 UTC
![305897433-9c1059cc-7562-403e-a4b4-6805141e9c4c](https://github.com/Satellile/yara/assets/36913431/864a10c2-4784-45fd-a771-132243660c45)
Getting errors from regen function. See the pic for the details. Thanks for the update!

**Comment by Satellile** [comment] 2024-02-21 21:53
Thanks for reporting this, any chance you could send me an example image that fails in this manner?

![test](https://github.com/Satellile/yara/assets/118775491/069e87e8-6b61-4954-9edb-ea97be1d44fe)

**Comment by charliebrown777** [comment] 2024-02-23 16:49
> Thanks for reporting this, any chance you could attach an example low-res image that fails in this manner?

Could you let me know your email address? I can mail it to you directly. Thanks!

**Comment by charliebrown777** [comment] 2024-02-28 16:06
![012551_01_sdxl_00001_](https://github.com/Satellile/yara/assets/36913431/37d1b56c-1362-46d9-9493-bbf801abf55a)
See attached. Thx.

**Comment by charliebrown777** [comment] 2024-03-01 06:12
Any updates?

**Comment by Satellile** [comment] 2024-03-01 23:45
Took a look, seems to be caused by some unexpected behavior from custom nodes. it should be fixed with [Yara v1.0.1](https://github.com/Satellile/yara/releases/tag/v1.0.1). I can't fully test it since I don't have the custom nodes installed, let me know if it works out!

The first issue seems to have been caused by the DynamicPrompt custom nodes, which have "NaN" values in the JSON prompt data. I've patched it quickly by adding a new dependency on the `json5` crate, and using that as a fallback.

The image still failed after that, though. It seems the ImageScaleBy node in the workflow has custom inputs - I'm expecting a text field, but it instead has a number. I've made a similar quick patch for that.

**Comment by charliebrown777** [comment] 2024-03-02 00:25
Thank you for your work!
I am doing a batch generation right on the way. I will test it when I start the 2nd pass generation and let you know the result.

**Comment by charliebrown777** [comment] 2024-03-02 09:55
![image](https://github.com/Satellile/yara/assets/36913431/8f58cf0a-1742-49be-b890-592b4658e6a8)
It seems it can read the json file this time but it says the node was not muted which is not true... Could you pls check with that? Much thanks!

**Comment by Satellile** [comment] 2024-03-02 17:24
Oops, I made a typo that caused muted nodes to be detected as unmuted and vice versa. Should be fixed in [yara v1.0.2](https://github.com/Satellile/yara/releases/tag/v1.0.2)

**Comment by charliebrown777** [comment] 2024-03-02 19:41
It's working 100% now. Gee... you don't know how much time you saved for me... Your work deserves a larger audience. Thank you!

**Comment by Satellile** [comment] 2024-03-03 04:19
No problem, glad it's helpful!

**Closed by Satellile** 2024-03-03 04:19 UTC
